name: ci
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libreadline-dev python3-setuptools pipx

      - name: install norminette
        run: |
          pipx install norminette
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Check formatting
        run: make format-check

      - name: Build (strict)
        run: make fclean all BUILD=strict
